export const CITY_SEARCH_RESET = "CITY_SEARCH_RESET"
export const CITY_SEARCH_SUCCESS = "CITY_SEARCH_SUCCESS"
export const CITY_SEARCH_FAIL = "CITY_SEARCH_FAIL"

export const UPDATE_CURRENT_CITY_RESET = "UPDATE_CURRENT_CITY_RESET"
export const UPDATE_CURRENT_CITY = "UPDATE_CURRENT_CITY"
