export const CONTACT_REQUEST = "CONTACT_REQUEST"
export const CONTACT_RESET = "CONTACT_RESET"
export const CONTACT_REQUEST_SUCCESS = "CONTACT_REQUEST_SUCCESS"
export const CONTACT_REQUEST_FAIL = "CONTACT_REQUEST_FAIL"