export const PRAYER_TIMES_BY_CITY_REQUEST = "PRAYER_TIMES_BY_CITY_REQUEST"
export const PRAYER_TIMES_BY_CITY_SUCCESS = "PRAYER_TIMES_BY_CITY_SUCCESS"
export const PRAYER_TIMES_BY_CITY_FAIL = "PRAYER_TIMES_BY_CITY_FAIL"